# Generated by Django 4.1.2 on 2023-09-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_codidobarras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='codidoBarras',
            new_name='codigoBarras',
        ),
    ]
