# Generated by Django 4.1.2 on 2023-11-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_codidobarras_producto_codigobarras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precioMayor',
            new_name='cantidad_x_empaque',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='codigoBarras',
            new_name='codigo_barras',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precioVenta',
            new_name='precio_venta',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_mayor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
