# Generated by Django 4.1.2 on 2024-03-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_rename_preciomayor_producto_cantidad_x_empaque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad_x_empaque',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
