# Generated by Django 4.1.2 on 2024-03-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_categoria_created_alter_categoria_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadoproducto',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
