# Generated by Django 4.1.2 on 2024-03-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_banco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocuentabancaria',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Cuenta Bancaria', 'verbose_name_plural': 'Tipos de cuenta bancaria'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.AddField(
            model_name='banco',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='creater',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='deleter',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banco',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banco',
            name='updater',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
