# Generated by Django 4.1.2 on 2024-03-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_alter_banco_created_alter_banco_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
