# Generated by Django 4.1.2 on 2023-08-30 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('barrio', models.CharField(blank=True, max_length=150, null=True)),
                ('ubcacionGPS', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('birthday', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('tipo_comercio', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta', models.CharField(blank=True, max_length=20, null=True)),
                ('orden_ruta', models.IntegerField(default=0)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.ciudad')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.tipodocumento')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre', models.CharField(max_length=25)),
                ('descipcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_preventa', models.DateTimeField()),
                ('valor_preventa', models.FloatField()),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.formapago')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preventa',
                'verbose_name_plural': 'preventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_venta', models.DateField()),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_vence', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.estadoventa')),
                ('forma_pago', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='baseapp.formapago')),
                ('preventa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.preventa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.FloatField()),
                ('descuento', models.FloatField(default=0)),
                ('iva', models.IntegerField(default=0)),
                ('neto', models.FloatField()),
                ('observacion', models.CharField(blank=True, max_length=250, null=True)),
                ('tarifa_aplicada', models.IntegerField()),
                ('costo', models.FloatField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'ventaDetalle',
                'verbose_name_plural': 'ventaDetalles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('creater', models.CharField(blank=True, max_length=30, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_pago', models.DateField()),
                ('valor_pago', models.FloatField()),
                ('nota', models.CharField(blank=True, max_length=250, null=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.formapago')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'pagoVenta',
                'verbose_name_plural': 'Pagosventa',
                'ordering': ['id'],
            },
        ),
    ]
