# Generated by Django 4.1.2 on 2023-11-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='ubcacionGPS',
            new_name='ubicacion_GPS',
        ),
    ]
