# Generated by Django 4.1.2 on 2024-04-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_rename_created_r_cliente_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadoventa',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
