# Generated by Django 4.1.2 on 2023-08-30 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creater', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updater', models.CharField(max_length=20)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'db_table': 'pedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=1)),
                ('state', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creater', models.CharField(max_length=20)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updater', models.CharField(max_length=20)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('deleter', models.CharField(max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedidoDetalle',
                'verbose_name_plural': 'pedidoDetalles',
                'db_table': 'pedidoDetalles',
                'ordering': ['id'],
            },
        ),
    ]
