# Generated by Django 4.1.2 on 2023-11-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='ubcacionGPS',
            new_name='ubicacion_GPS',
        ),
        migrations.AlterField(
            model_name='compradetalles',
            name='descuento_pos_iva',
            field=models.FloatField(default=0, verbose_name='Desc pos'),
        ),
        migrations.AlterField(
            model_name='compradetalles',
            name='descuento_pre_iva',
            field=models.FloatField(default=0, verbose_name='Desc pre'),
        ),
        migrations.AlterField(
            model_name='compradetalles',
            name='flete',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6),
        ),
    ]
