# Generated by Django 4.1.2 on 2024-03-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_rename_ubcaciongps_proveedor_ubicacion_gps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='compradetalles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='compradetalles',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadocompra',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadocompra',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
