# Generated by Django 4.1.2 on 2024-04-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_created_r_compra_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadocompra',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
